services:
  markdown-viewer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
      - ./server:/app/server
      - /app/server/node_modules
      - ./files:/app/files
    environment:
      - NODE_ENV=development
      - PORT=3002
      - FILES_DIR=/app/files
